### ISSUE TITLE
View-5 Our projects Page

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QuestionPaper_Frontend#6]
Our projects should be available as cards, with different visually appealing designs.

**Comment by AkbarHabeeb** [comment]
The page should display all our projects as cards(responsive) inside that there should be an image for each project, repo url, tech stack, primary devs and short description.

Clone the repo
Understand the code
Add a view for projects
Create a design and get it reviewed from us
Code it
Send a PR

1. 

1.

**Comment by keerthinayana** [comment]
What is meant by tech stack and primary devs?
